### ISSUE TITLE
page not found error

### ISSUE THREAD

**Issue by swrdfish** [reactioncommerce/reaction-example-plugin#1]
If I include this plugin, then I get a page not found error. I was following the tutorial which also resulted in  the same error.

Is there a way to debug it?

**Comment by swrdfish** [comment]
restarting the server solved the issue.. please update the code to be put inside `register.js` in the [Creating a plugin](https://docs.reactioncommerce.com/reaction-docs/master/creating-a-plugin) guide.

**Comment by tobitech** [comment]
I'm still getting Page Not Found Error... after restarting the server. I'm not sure I know exactly where to add the imports for the init.js file, can you help with that?

**Comment by swrdfish** [comment]
The [forum]( https://forums.reactioncommerce.com/) will be a better place for such questions.
