### ISSUE TITLE
Receive error when visiting home page as admin

### ISSUE THREAD

**Issue by brent-hoover** [reactioncommerce/reaction-example-plugin#10]
### Expected Behavior
 No error in console

### Actual Behavior
Error in console

### Steps to Reproduce
1. Drop plugin into current RC.
1. Login as admin
1. Observe error in console

**Comment by aaronjudd** [comment]
ie " reaction example plugins don't work", fix it...

**Comment by brent-hoover** [comment]
What moron didn't put what the error was in the ticket? Anyway, I think this is fixed in #16
