### ISSUE TITLE
Footer template is not shown on the Product Detail Page

### ISSUE THREAD

**Issue by janus-reith** [reactioncommerce/reaction-example-plugin#15]
Same issue that occured when following the previous tutorial in the docs, that still used a blaze template for the core layout.

How to make the footer appear on the PDP?

**Comment by josx** [comment]
same problem here, any clue to fix it?

**Comment by prinzdezibel** [comment]
Done.

**Comment by prinzdezibel** [comment]
Reopening. Actually I was wrong with my assumption that this works now. It's rather a matter of fact, that PDP does per default NOT show the footer. There's a PR for it, but it's not review yet.
