### ISSUE TITLE
No such template: productGrid

### ISSUE THREAD

**Issue by neeraj022** [reactioncommerce/reaction-example-plugin#17]
After applying this plugin and restarting the reaction commerce server, I am getting the following error:
```
Error: No such template: productGrid
    at blaze.js?hash=f33d3df…:3212
    at Blaze.View.<anonymous> (spacebars.js?hash=ebf9381…:68)
    at blaze.js?hash=f33d3df…:1934
    at Function.Template._withTemplateInstanceFunc (blaze.js?hash=f33d3df…:3744)
    at blaze.js?hash=f33d3df…:1932
    at Object.Blaze._withCurrentView (blaze.js?hash=f33d3df…:2271)
    at viewAutorun (blaze.js?hash=f33d3df…:1931)
    at Tracker.Computation._compute (tracker.js?hash=997515f…:339)
    at new Tracker.Computation (tracker.js?hash=997515f…:229)
    at Object.Tracker.autorun (tracker.js?hash=997515f…:613)
```

**Comment by brent-hoover** [comment]
Yeah, I am seeing this as well. The `productGrid` template was removed in the last couple of releases and replaced with a React component. We are going to re-write this to use the new registerComponent API but that's not in the current release. Not sure what an interim solution is but I will see what I can do.

**Comment by rovincent** [comment]
Was there any update on this ?

**Comment by machikoyasuda** [comment]
Hi @rovincent @neeraj022 - Thanks for reporting this issue. The 1.4 release brings back the `productGrid` as a React component. Try testing this plugin on the latest `marketplace` branch: https://github.com/reactioncommerce/reaction/tree/marketplace - it should be working there.

**Comment by alineah** [comment]
Hi, 
I have exactly the same issue. The tutorial is not working anymore.
I have tested with the marketplace branch. However it brings others issues.
First, new packages need to be install manually: 
`meteor npm install --save recompose connect body-parser connect-query bcrypt connect-route shopify-api-node`

Second, after running reaction and reloading the homepage I have the following errors:

> modules.js:517 'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.copyKey @ modules.js:517
> modules.js:517 'webkitIndexedDB' is deprecated. Please use 'indexedDB' instead.copyKey @ modules.js:517
> modules.js:98364 Download the React DevTools for a better development experience: https://fb.me/react-devtools
> app.js:47908 DEPRECATED registerComponent(). Use new implementation. see: https://docs.reactioncommerce.com/reaction-docs/master/components-api_registerComponent @ app.js:47908
> meteor.js:934 Exception from Tracker recompute function:
> **meteor.js:934 TypeError: Cannot read property 'language' of undefined**
>     at app.js:109748
>     at Tracker.Computation._compute (tracker.js:339)
>     at Tracker.Computation._recompute (tracker.js:358)
>     at Object.Tracker._runFlush (tracker.js:532)
>     at onGlobalMessage (meteor.js:401)

Do you have any idea of what I should do to resolve the issue ? I'm just following the tutorial:
https://docs.reactioncommerce.com/reaction-docs/master/plugin-customizing-templates-4

Thanks

**Comment by josx** [comment]
is there any workaround with current master version?

**Comment by josx** [comment]
Here same problem when upgrading to RC 1.4 version (https://github.com/carlos-olivera/Next-Reaction/issues/1)
