### ISSUE TITLE
Reaction init VS tutorial

### ISSUE THREAD

**Issue by alineah** [reactioncommerce/reaction-example-plugin#19]
Hello, 
I'm trying to learn Reaction and I'm following the documentation.
However, it seems installing reaction how it is described in https://docs.reactioncommerce.com/reaction-docs/master/installation leads to a unstable version of Reaction. See the following issue as an example:
https://github.com/reactioncommerce/reaction-example-plugin/issues/17

Is it only a tutorial issue ?
Is there any option to get the last stable version using "reaction init" ?
Could you update the documentation so newbies can start working with Reaction again ?

I'm concern about Reaction plugins. An argument to use them is: "implement your plugins, no need to change the core, only pull the latest core version, your plugins will still work". However, it seems not the case.

Thanks for your help.

**Comment by machikoyasuda** [comment]
Hi @uncanard - I'm sorry you've been running into issues with our now outdated tutorial. We're in the middle of updating it.

To answer your other question, you can use the `reaction` CLI tool so you can initialize a reaction project with a different _branch_ of reaction. If you wanted to use the `marketplace` branch, for example, you would run: ```reaction init --branch marketplace``` There's no support for different release tags yet.

**Comment by alineah** [comment]
Thanks.
Do you have any example of simple working plugin on the marketplace branch ?

**Comment by brent-hoover** [comment]
Closing as the `marketplace` branch has been removed and `master` is stable.
