### ISSUE TITLE
Page reloads on route.

### ISSUE THREAD

**Issue by harshalyeole-tudip** [reactioncommerce/reaction-example-plugin#26]
Hi,

I have added example plugin the in the custom directory. And added new route namely "/addRecipe" 
with following code:

1. In _/client/templates/layouts/core.js_ file
`<a href={Reaction.Router.pathFor("addRecipe")}>Add Recipe</a>`
2. In registry of  _register.js_ file
`{
      route: "/addRecipe",
      name: "addRecipe",
      template: "addRecipe",
      workflow: "coreProductGridWorkflow"
    }`

**With the above code modifications, when I click on the "Add Recipe" link, page is _reloaded_.**

How do I make it in such a way that it does not reload on routing, like we click on the "SHOP" from home page, the page never reloads.

**Comment by harshalyeole-tudip** [comment]
Any update here?

**Comment by harshalyeole-tudip** [comment]
Hey,

I'm not having this issue on navigation via the tag.

I'm getting issue on "About Us" link.

**Comment by prinzdezibel** [comment]
@harshalyeole-tudip  Sorry for confusion, I was talking about the `anchor tag`. You need to handle route changes in an event handler, e.g.
```
 <a href="#" onClick={(event) => {
             event.preventDefault();
             const path = Reaction.Router.pathFor("about");
             Reaction.Router.go(path);
             return false;
           }
         }>About Us</a>
```
This will solve your problem.

**Comment by harshalyeole-tudip** [comment]
That helps!

Thanks.
