### ISSUE TITLE
Help understanding the template mapping with a Custom Nav

### ISSUE THREAD

**Issue by hydrotik** [reactioncommerce/reaction-example-plugin#3]
Hi there, I am using this as a foundation for creating a custom plugin to help understand the process by which the templates are pulled in. For example I want to include this component to override the default layout nav/brand logic

``` html
<template name="navigationBrandCustom">
  <a class="brand" href="{{pathFor '/'}}" title="{{siteName}}">
    {{#if logo}}
      <div class="logo">
        <img src="{{logo.url}}" alt="{{siteName}}">
      </div>
    {{else}}
      <span class="title">{{siteName}}</span>
    {{/if}}
  </a>
</template>
```

Is it possible to get a little info on how to wire this up into the plugin? I've tried a number of options and at the moment I am seeing a "This site requires JavaScript. Please enable it in your browser settings." message.

```
[Error] Blocked script execution in 'http://localhost:3000/' because the document's frame is sandboxed and the 'allow-scripts' permission is not set. (x142)
```

I would expect to change the layoutHeader value to my header template, but that doesn't seem to work in:

``` html
import { Reaction } from "/server/api";

// Register package as ReactionCommerce package
Reaction.registerPackage({
  label: "Hydrotik",
  name: "hydrotik",
  icon: "fa fa-vine",
  autoEnable: true,
  registry: [
    {
      route: "/about",
      name: "about",
      template: "aboutUs",
      workflow: "coreWorkflow"
    }
  ],
  layout: [{
    layout: "layoutCustom",
    workflow: "coreWorkflow",
    collection: "Products",
    theme: "default",
    enabled: true,
    structure: {
      template: "productsLanding",
      layoutHeader: "layoutHeader",
      layoutFooter: "layoutFooter",
      notFound: "productNotFound",
      dashboardHeader: "",
      dashboardControls: "dashboardControls",
      dashboardHeaderControls: "",
      adminControlsFooter: "adminControlsFooter"
    } }
  ]
});
```

**Comment by hydrotik** [comment]
[hydrotik.zip](https://github.com/reactioncommerce/reaction-example-plugin/files/520989/hydrotik.zip)

**Comment by hydrotik** [comment]
[hydrotik.zip](https://github.com/reactioncommerce/reaction-example-plugin/files/520990/hydrotik.zip)

**Comment by brent-hoover** [comment]
@hydrotik The name of the template you create must match the value you have in the registry. Do you have a template called `layoutCustom`?

I think what you really want to override would be the `layoutHeader` value.

**Comment by hydrotik** [comment]
``` html
<template name="layoutCustom">
{{#if hasDashboardAccess}}
  {{> coreAdminLayout}}
{{else}}
    <nav class="reaction-navigation-header">
      <!-- begin layoutHeader -->
      {{> Template.dynamic template=headerCustom}}
      <!-- end layoutHeader -->
    </nav>

    <nav class="reaction-cart-drawer">
      {{>cartDrawer}}
    </nav>

  <main role="main" id="main">
    <p>This is the Bee's Knees layout</p>
    <span id="layout-alerts">{{> inlineAlerts}}</span>
    {{#if hasPermission 'guest'}}
      <!-- begin template region -->
      {{> Template.dynamic template=template}}
      <!-- end template region -->
    {{/if}}

    <footer class="reaction-navigation-footer footer-default">{{> Template.dynamic template=footerCustom}}</footer>
  </main>

{{/if}}
</template>
```

I will see if I can override header, but I do have layoutCustom which links to the headerCustom and footerCustom.

**Comment by hydrotik** [comment]
Is there any more info on the keys that structure is using? I will look in the docs, but I'm assuming these are standards set forth by the Reaction application structure?

``` js
layout: [{
    layout: "layoutCustom",
    workflow: "coreWorkflow",
    collection: "Products",
    theme: "default",
    enabled: true,
    structure: {
      template: "productsLanding",
      layoutHeader: "headerCustom",
      layoutFooter: "footerCustom",
      notFound: "productNotFound",
      dashboardHeader: "",
      dashboardControls: "dashboardControls",
      dashboardHeaderControls: "",
      adminControlsFooter: "adminControlsFooter"
    } }
  ]
```

**Comment by brent-hoover** [comment]
Your problem is here: 
`{{> Template.dynamic template=footerCustom}}`

That used to say `template=layoutFooter` and that is the **variable name** not the name of the template. The variable `layoutFooter` is being passed and it's value it set to whatever you set it to  in `register.json`. If you change it, it's just never going to work. Change it back to `layoutFooter` and set the name of the template in your register.js.

**Comment by hydrotik** [comment]
This was very helpful in clarifying the mapping, thank you. I made the change, but I am still a whoops not found page showing with no errors. I will keep working on it and if share if I find the solution.

**Comment by hydrotik** [comment]
So in this project, shouldn't

``` javascript
import { Reaction } from "/server/api";

// Register package as ReactionCommerce package
Reaction.registerPackage({
  label: "Bees Knees",
  name: "beesknees",
  icon: "fa fa-vine",
  autoEnable: true,
  registry: [
    {
      route: "/about",
      name: "about",
      template: "aboutUs",
      workflow: "coreWorkflow"
    }
  ],
  layout: [{
    layout: "coreLayoutBeesknees",
    workflow: "coreWorkflow",
    collection: "Products",
    theme: "default",
    enabled: true,
    structure: {
      template: "productsLanding",
      layoutHeader: "layoutHeader",
      layoutFooter: "layoutFooter",
      notFound: "productNotFound",
      dashboardHeader: "",
      dashboardControls: "dashboardControls",
      dashboardHeaderControls: "",
      adminControlsFooter: "adminControlsFooter"
    } }
  ]
});
```

be

``` javascript
import { Reaction } from "/server/api";

// Register package as ReactionCommerce package
Reaction.registerPackage({
  label: "Bees Knees",
  name: "beesknees",
  icon: "fa fa-vine",
  autoEnable: true,
  registry: [
    {
      route: "/about",
      name: "about",
      template: "aboutUs",
      workflow: "coreWorkflow"
    }
  ],
  layout: [{
    layout: "coreLayoutBeesknees",
    workflow: "coreWorkflow",
    collection: "Products",
    theme: "default",
    enabled: true,
    structure: {
      template: "productsLanding",
      layoutHeader: "layoutHeader",
      // here
      layoutFooter: "layoutFooterBeesKnees",
      notFound: "productNotFound",
      dashboardHeader: "",
      dashboardControls: "dashboardControls",
      dashboardHeaderControls: "",
      adminControlsFooter: "adminControlsFooter"
    } }
  ]
});
```

**Comment by brent-hoover** [comment]
If I wanted to override the footer template, yes.

**Comment by hydrotik** [comment]
So when I get the page not found I don't see any errors, also having set everything up from what I see is consistent with the logic you have been helpful in explaining, I get that or this:

[Error] Blocked script execution in 'http://localhost:3000/' because the document's frame is sandboxed and the 'allow-scripts' permission is not set. (x142)

Is there a more effective way to debug? like a reaction --verbose or something?

**Comment by brent-hoover** [comment]
Have you run `reaction reset`?

**Comment by brent-hoover** [comment]
Reaction is already pretty verbose. But you can run `reaction debug` to run Meteor in [debug](http://joshowens.me/easily-debugging-meteor-js/) mode.

**Comment by hydrotik** [comment]
Doesn't seem to be helping much. I even restarted my computer lol. I have simplified it down to this:

``` javascript
import { Reaction } from "/server/api";

// Register package as ReactionCommerce package
Reaction.registerPackage({
  label: "Hydrotik",
  name: "hydrotik",
  icon: "fa fa-vine",
  autoEnable: true,
  registry: [
    {
      route: "/about",
      name: "about",
      template: "aboutUs",
      workflow: "coreWorkflow"
    }
  ],
  layout: [{
    layout: "layoutCustomHydrotik",
    workflow: "coreWorkflow",
    collection: "Products",
    theme: "default",
    enabled: true,
    structure: {
      template: "productsLanding",
      layoutHeader: "layoutHeader",
      layoutFooter: "layoutFooter",
      notFound: "productNotFound",
      dashboardHeader: "",
      dashboardControls: "dashboardControls",
      dashboardHeaderControls: "",
      adminControlsFooter: "adminControlsFooter"
    } }
  ]
});
```

and in layout.html

``` html
<template name="layoutCustomHydrotik">
Hello Template
</template>
```

client/index.js

``` javascript
import "./templates";
import "./defaults";
import "./styles/main.less";
```

and in client/templates/index.js

``` javascript
// checkout
import "./checkout/review/review.html";
import "./checkout/review/review";

// layouts
import "./layout/layout.html";
//import "./layout/header/header.html";
//import "./layout/header/header";
import "./layout/footer/footer.html";

// products
import "./products/productsLanding.html";
import "./products/productsLanding";

// static
import "./static/aboutus.html";
```

and still getting the oops page not found. nothing in browser console and nothing in terminal. I guess I will try to go back to the original plugin example and try to rebuild it from that again. Thanks for the help so far @zenweasel!

**Comment by brent-hoover** [comment]
What's the URL you can trying to visit locally?

**Comment by hydrotik** [comment]
http://localhost:3000/

![screen shot 2016-10-12 at 8 09 36 pm](https://cloud.githubusercontent.com/assets/157727/19332235/26821048-90b8-11e6-96d2-4f3ac1adb130.png)

**Comment by brent-hoover** [comment]
Yeah, something is really wrong there. This would be a lot easier to troubleshoot with you if we did this through chat rather than a GH issue.

**Comment by hydrotik** [comment]
So I've narrowed it down to something with the pathing to components that I added and have isolated the 404 so I am at least seeing the site load with that code pulled out.

One thing that I am a little unsure about is with this example plugin, why the footer wouldn't be showing? It's in the registry under structure, but I don't see where the value for the layoutFooter var you mentioned above is defined. I tried doing something like:

``` javascript
import { Session } from "meteor/session";
import { Logger } from "/client/api";

Session.set("DEFAULT_LAYOUT", "coreLayoutBeesknees");
Logger.info("setting DEFAULT_LAYOUT");

Session.set("layoutFooter", "layoutFooterBeesKnees");
```

in defaults, but that didn't work. And again, changing layoutFooter to layoutFooterBeesKnees in register.js didn't do anything. I feel like this should be a little bit more intuitive.

**Comment by hydrotik** [comment]
Also if you could explain why doing something simple like:

``` html
<footer class="reaction-navigation-footer footer-default">{{> Template.dynamic template=layoutFooterBeesKnees}}</footer>
```

Doesn't work?

**Comment by brent-hoover** [comment]
It's because the value there is not the name of the template, but the name of the variable. If you change the variable name it's not going to work. It's a dynamic template, so you provide it with a variable name that will contain the template name, not the template name itself.

**Comment by hydrotik** [comment]
That makes sense, which is why I would assume that a control process for overriding default templates such as:

``` javascript
Session.set("DEFAULT_FOOTER", "layoutFooterBeesKnees");
```

would exist somewhere? I'm trying to find more info around the Session.set and constants, but wondering if I'm barking up the wrong tree.

**Comment by hydrotik** [comment]
Should the footer link be taking you to the static template in about us?

**Comment by hydrotik** [comment]
I pushed some changes to my test plugin  at https://github.com/hydrotik/reaction-hydrotik-plugin trying to bring the header in. What seems like logic from our previous discussions, doesn't seem to be working. Would it be something in server/init?

**Comment by brent-hoover** [comment]
Do you have your changes pushed, because I see neither a header template nor an import for it.

**Comment by hydrotik** [comment]
https://github.com/hydrotik/reaction-hydrotik-plugin/commit/ef294e6405db9d8f3b2e41b6e136a348620935de

**Comment by brent-hoover** [comment]
Running your code I see the header showing.
<img width="447" alt="reaction" src="https://cloud.githubusercontent.com/assets/72819/19422693/fa0f4eae-944a-11e6-9c07-a645afdfba91.png">

**Comment by brent-hoover** [comment]
As I mentioned before, could we please move this to the Gitter chat room? Doing support through an issue like this is very painful for me and no one else benefits from seeing the history.

**Comment by hydrotik** [comment]
![screen shot 2016-10-16 at 9 51 23 pm](https://cloud.githubusercontent.com/assets/157727/19423101/ff008442-93ea-11e6-8ad2-ea600c6a42f8.png)

**Comment by brent-hoover** [comment]
Conversation moved to Gitter.
