### ISSUE TITLE
Error No such template: productList.

### ISSUE THREAD

**Issue by NurdinDev** [reactioncommerce/reaction-example-plugin#32]
I apply the theme to learn and to make some customizing on it, It's work right like this but when I need to know what this block start in line 7 does [https://github.com/reactioncommerce/reaction-example-plugin/blob/master/client/templates/products/productsLanding.html](url) 

I add the template name to register file "productListGridBeesKnees" instead of "productsLanding", not work after login because of the "productList" template not found. 

first, I need to know whey "productList" not found?
and what is this block dose?

thank you, and sorry to write an issue.

**Comment by brent-hoover** [comment]
@nuruddinXbadawi Are you using the most recent version of Reaction? The example plugin will always only work with the newest version, which is currently `1.10.0`.

**Comment by NurdinDev** [comment]
![screen shot 2018-03-28 at 8 51 34 am](https://user-images.githubusercontent.com/5736522/38011214-3a3809b2-3265-11e8-9cf5-a9d458af74c1.png)

are you using this template "productListGridBeesKnees" in your theme? I didn't find it when I search this template not used and not load at all, correct me if I make wrong, and thank you.
