### ISSUE TITLE
i18n import doesn't exist

### ISSUE THREAD

**Issue by jshimko** [reactioncommerce/reaction-example-plugin#7]
This function doesn't exist (at that import or anywhere else in the app) and calling it here crashes the app. 
https://github.com/reactioncommerce/reaction-example-plugin/blob/master/server/i18n/index.js#L1

And the [similarly named function that is there](https://github.com/reactioncommerce/reaction/blob/master/server/startup/i18n.js#L15) doesn't take any arguments and isn't intended for the use case this plugin is trying to use it for.

**Comment by brent-hoover** [comment]
It's right here: https://github.com/reactioncommerce/reaction/blob/8e5eb79991cc8dfd2f8a35a4a0fc6c98078a6469/server/startup/i18n.js#L53-L53

Closing.
